# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazyntkanin.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dziennik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('data', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dzienniki',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=500)),
                ('funkcja', models.CharField(max_length=70)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dziennik_nr', models.IntegerField(default=None, null=True)),
                ('wpis_szwalnia_id', models.IntegerField(default=None, null=True)),
                ('rolka_id', models.IntegerField(default=None, null=True)),
                ('index_tkaniny', models.IntegerField(default=None, null=True)),
                ('dlugosc_rolki', models.FloatField(default=None, null=True)),
                ('nr_fgk', models.CharField(max_length=30)),
                ('dlugosc_elementu', models.FloatField(default=None, null=True)),
                ('typ', models.CharField(default=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logi',
            },
        ),
        migrations.CreateModel(
            name='Odpad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Odpad',
                'verbose_name_plural': 'Odpady',
            },
        ),
        migrations.CreateModel(
            name='Paczki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karta', models.CharField(max_length=50)),
                ('pozycja', models.CharField(max_length=50)),
                ('zakonczona', models.BooleanField(default=False)),
                ('tkanina', models.CharField(default='', max_length=50)),
                ('data_utworzenia', models.DateTimeField(blank=True, default=None, null=True)),
                ('dziennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Dziennik')),
            ],
            options={
                'verbose_name': 'Paczki',
                'verbose_name_plural': 'Paczki',
            },
        ),
        migrations.CreateModel(
            name='Rolka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Magazyn'), (1, 'Wydany'), (2, 'Zakończony')], default=0)),
                ('wydanie', models.IntegerField(choices=[(0, 'Wydanie wewnętrzne'), (1, 'Wymianka'), (2, 'Sprzedaż'), (3, 'Wzorniki')], default=0)),
                ('data_dostawy', models.DateField(blank=True, default=None, null=True)),
                ('lot', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_rolki', models.IntegerField(default=0)),
                ('dlugosc', models.FloatField(default=0)),
                ('szerokosc', models.IntegerField(default=0)),
                ('dlugosc_poczatkowa', models.FloatField(blank=True, null=True)),
                ('barcode', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nr_zamowienia', models.CharField(blank=True, max_length=50, null=True)),
                ('zakonczona', models.BooleanField(default=False)),
                ('wydrukowana', models.BooleanField(default=False)),
                ('do_usuniecia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Rolki',
            },
        ),
        migrations.CreateModel(
            name='Rolka_usunieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Magazyn'), (1, 'Wydany'), (2, 'Zakończony')], default=0)),
                ('wydanie', models.IntegerField(choices=[(0, 'Wydanie wewnętrzne'), (1, 'Wymianka'), (2, 'Sprzedaż'), (3, 'Wzorniki')], default=0)),
                ('data_dostawy', models.DateField(blank=True, default=None, null=True)),
                ('lot', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_rolki', models.IntegerField(default=0)),
                ('dlugosc', models.FloatField(default=0)),
                ('szerokosc', models.IntegerField(default=0)),
                ('dlugosc_poczatkowa', models.FloatField(blank=True, null=True)),
                ('barcode', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nr_zamowienia', models.CharField(blank=True, max_length=50, null=True)),
                ('zakonczona', models.BooleanField(default=False)),
                ('wydrukowana', models.BooleanField(default=False)),
                ('do_usuniecia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Rolki usuniete',
            },
        ),
        migrations.CreateModel(
            name='Rolka_zliczana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Magazyn'), (1, 'Wydany'), (2, 'Zakończony')], default=0)),
                ('wydanie', models.IntegerField(choices=[(0, 'Wydanie wewnętrzne'), (1, 'Wymianka'), (2, 'Sprzedaż'), (3, 'Wzorniki')], default=0)),
                ('data_dostawy', models.DateField(blank=True, default=None, null=True)),
                ('lot', models.CharField(blank=True, max_length=30, null=True)),
                ('nr_rolki', models.IntegerField(default=0)),
                ('dlugosc', models.FloatField(default=0)),
                ('szerokosc', models.IntegerField(default=0)),
                ('dlugosc_poczatkowa', models.FloatField(blank=True, null=True)),
                ('barcode', models.BigIntegerField(blank=True, default=None, null=True)),
                ('nr_zamowienia', models.CharField(blank=True, max_length=50, null=True)),
                ('zakonczona', models.BooleanField(default=False)),
                ('wydrukowana', models.BooleanField(default=False)),
                ('do_usuniecia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Rolki zliczane',
            },
        ),
        migrations.CreateModel(
            name='Stoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.IntegerField()),
                ('ilosc', models.FloatField(default=0)),
                ('dziennik', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Dziennik')),
                ('rolka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Rolka')),
            ],
            options={
                'verbose_name': 'Stoff',
                'verbose_name_plural': 'Stoffy',
            },
        ),
        migrations.CreateModel(
            name='Tkanina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sap', models.IntegerField(unique=True)),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tkaniny',
            },
        ),
        migrations.CreateModel(
            name='TkaninyXlsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='magazyntkanin/pliki/euro', validators=[magazyntkanin.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_dostawy', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WpisyMagazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.FloatField(default=0)),
                ('dziennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Dziennik')),
                ('tkanina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Tkanina')),
            ],
            options={
                'verbose_name_plural': 'Wpisy dziennika - Magazyn',
            },
        ),
        migrations.CreateModel(
            name='WpisyMagazynPowiazania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywne', models.BooleanField(default=False)),
                ('data_wydania', models.DateTimeField(auto_now_add=True)),
                ('data_zwrotu', models.DateTimeField(blank=True, default=None, null=True)),
                ('dziennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Dziennik')),
                ('rolka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Rolka')),
            ],
            options={
                'verbose_name': 'Powiazanie z magazynem',
                'verbose_name_plural': 'Powiazania magazynowe',
            },
        ),
        migrations.CreateModel(
            name='WpisySzwalnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.IntegerField()),
                ('TA', models.IntegerField()),
                ('ilosc', models.IntegerField()),
                ('tura', models.IntegerField()),
                ('ukonczone', models.BooleanField(default=False)),
                ('dziennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Dziennik')),
                ('tkanina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Tkanina')),
            ],
            options={
                'verbose_name_plural': 'Wpisy dziennika - Szwalnia',
            },
        ),
        migrations.AddField(
            model_name='rolka_zliczana',
            name='tkanina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Tkanina'),
        ),
        migrations.AddField(
            model_name='rolka_usunieta',
            name='tkanina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Tkanina'),
        ),
        migrations.AddField(
            model_name='rolka',
            name='tkanina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Tkanina'),
        ),
        migrations.AddField(
            model_name='odpad',
            name='rolka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyntkanin.Rolka'),
        ),
    ]
